name: Benchmark
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: benchmark
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Memcached server
        run: docker run -d -p 11211:11211 --name memcached memcached:1.6.18-alpine
      - name: Compile
        run: mvn package -DskipTests
      - name: Run benchmark
        run: java -jar memkched-benchmark/target/benchmarks.jar
      - name: Shutdown
        if: always()
        run: docker stop memcached && docker rm memcached
