name: Linters
on:
  pull_request:

concurrency:
  group: linter-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: GH Actions lint
        uses: reviewdog/action-actionlint@v1
      - name: Detekt
        uses: alaegin/Detekt-Action@v1.23.1
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: build-config/detekt/detekt.yml
          detekt_baseline: build-config/detekt/baseline.xml
