name: Publish SNAPSHOT to Nexus
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: publish-snapshot
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      # Tests
      - name: Print
        run: cat ~/.m2/settings.xml
      # Tests
      - name: Verify
        run: mvn clean install

      # Publish snapshot
      - name: Publish package
        run: mvn --batch-mode -pl -memkched-benchmark clean dokka:dokka jar:jar@dokka-jar dokka:javadocJar source:jar deploy -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
