name: CI that generates SNAPSHOT
push:
  branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # Tests
      - name: Verify & Install
        run: mvn clean install

      # Doc generation
      - name: Generate Dokka
        run: mvn dokka:dokka jar:jar@dokka-jar
      - name: Generate Javadoc
        run: mvn dokka:javadocJar

      # Publish snapshot
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
