name: Preintegration
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Tests
      - name: Verify
        run: mvn verify

      # Doc generation
      - name: Generate Dokka
        run: mvn dokka:dokka jar:jar@dokka-jar
      - name: Generate Javadoc
        run: mvn dokka:javadocJar
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Memcached server
        run: docker run -d -p 11211:11211 --name memcached memcached:1.6.18-alpine
      - name: Run benchmark
        run: java -jar memkched-benchmark/target/benchmarks.jar
      - name: Shutdown
        if: always()
        run: docker stop memcached && docker rm memcached
