name: Pre-integration
on:
  pull_request

concurrency:
  group: pre-integration-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Tests
      - name: Verify & Install
        run: mvn clean dokka:dokka jar:jar@dokka-jar dokka:javadocJar source:jar install
