name: Preintegration
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Tests
      - name: Verify
        run: mvn verify

      # Doc generation
      - name: Generate Dokka
        run: mvn dokka:dokka jar:jar@dokka-jar
      - name: Generate Javadoc
        run: mvn dokka:javadocJar