name: Publish release to Nexus
on:
  release:
    types: [created]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # Tests
      - name: Verify & Install
        run: mvn clean install

      # Prepare for release
      - name: Prepare release
        run: mvn --batch-mode release:prepare

      # Publish
      - name: Publish package
        run: mvn --batch-mode -pl -memkched-benchmark clean dokka:dokka jar:jar@dokka-jar dokka:javadocJar source:jar release:perform -Dmaven.test.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
